// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVsy4ZdRLW4tK916RhfTcZoaqapBuSLpA',
    appId: '1:77975695178:web:a066149738098796591bb3',
    messagingSenderId: '77975695178',
    projectId: 'wallpaper-login-d9f9f',
    authDomain: 'wallpaper-login-d9f9f.firebaseapp.com',
    storageBucket: 'wallpaper-login-d9f9f.appspot.com',
    measurementId: 'G-TG5CZD9PSM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsejU2TJW0NscEmvS6CsehHPbcB1Av-DY',
    appId: '1:77975695178:android:d00907673d6f4785591bb3',
    messagingSenderId: '77975695178',
    projectId: 'wallpaper-login-d9f9f',
    storageBucket: 'wallpaper-login-d9f9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHXyxJigh2oNnalvyLjhCapL0YEUtpFrI',
    appId: '1:77975695178:ios:09092706b4ce9c9f591bb3',
    messagingSenderId: '77975695178',
    projectId: 'wallpaper-login-d9f9f',
    storageBucket: 'wallpaper-login-d9f9f.appspot.com',
    iosClientId: '77975695178-lj4jpg0h7roaqtp7ase7lsmi4airf5vq.apps.googleusercontent.com',
    iosBundleId: 'com.example.wallpapersHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHXyxJigh2oNnalvyLjhCapL0YEUtpFrI',
    appId: '1:77975695178:ios:c5a8c629a95062a5591bb3',
    messagingSenderId: '77975695178',
    projectId: 'wallpaper-login-d9f9f',
    storageBucket: 'wallpaper-login-d9f9f.appspot.com',
    iosClientId: '77975695178-ppk1odu72aak1tu2vp15bi9o1ofnievr.apps.googleusercontent.com',
    iosBundleId: 'com.codetify.pp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVsy4ZdRLW4tK916RhfTcZoaqapBuSLpA',
    appId: '1:77975695178:web:e9e1d90e3cbc852b591bb3',
    messagingSenderId: '77975695178',
    projectId: 'wallpaper-login-d9f9f',
    authDomain: 'wallpaper-login-d9f9f.firebaseapp.com',
    storageBucket: 'wallpaper-login-d9f9f.appspot.com',
    measurementId: 'G-4QJJGG5YP0',
  );
}
